In [28]:
import scipy.io as scio
import numpy as np    
import matplotlib.pyplot as plt
from scipy.misc import imsave

In [29]:
path='../../RetinalLayerSegmentationBackup/Dataset/Subject_new_'
labeled_images = []
labeled_colorimages = []
images_modified=[]

In [30]:
def load_subject(subject_no):
    local_path=path+subject_no+'/Sub_'+subject_no+'.mat'
    sub = scio.loadmat(local_path)
    print (sub.keys())
    return sub
    
def reshape(ndarray):
    ndarray_reshaped = np.array(ndarray.tolist())
    ndarray_reshaped = ndarray_reshaped.reshape(ndarray.shape).transpose(2,0,1)
    print (ndarray_reshaped.shape)
    return ndarray_reshaped

def get_gt_ids(subject_no):
    local_path=path+subject_no+'/gt_id.mat'
    gt_id = scio.loadmat(local_path)
    print (gt_id.keys())
    gt_id_list = gt_id['fr1']
    print(gt_id_list)
    gt_list = []
    for item in gt_id_list:
        gt_list.append(item[0])
    return gt_list
    
def crop_image(image,left_bound,right_bound):
    image = image[:,left_bound:right_bound]
    return image
    

In [31]:
sub = load_subject(str(2))
sub_images = sub['images']


['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']


In [32]:
for sub_index in range(10):
    sub=load_subject(str(sub_index+1))
    sub_images = sub['images']
    images_reshaped = reshape(sub_images)
    print (images_reshaped.shape)
    manualLayer = sub['manualLayers1']
    manualLayer_reshaped=reshape(manualLayer)
    print (manualLayer_reshaped.shape)
    left_bounds = [138,123,119,111,139,148,136,122,126,142]
    right_bounds = [634,619,615,607,635,644,632,618,622,638]
    gt_id_list = []
    gt_id_list = get_gt_ids(str(sub_index+1))
    for i in gt_id_list:
        test = manualLayer_reshaped[i-1]
        #print (test)
        test=crop_image(test,left_bounds[sub_index],right_bounds[sub_index])
        image_modified=crop_image(images_reshaped[i-1],left_bounds[sub_index],right_bounds[sub_index])
        images_modified.append(image_modified)
        for j in range(8):
            for k in range(496):
                if(test[j][k]==0):
                    test[j][k] = test[j][k-1]
        res_image = np.zeros((496,496))
        color = np.zeros((496,496,3))
        for j in range(7):
            for k in range(496):
                for a in range(test[j][k], test[j+1][k]):
                        res_image[a][k] = j+1
        labeled_images.append(res_image)
        for j in range(496):
            for k in range(496):
                if(res_image[j][k]==0):
                    color[j][k] = [0,0,0]
                if(res_image[j][k]==1):
                    color[j][k] = [128,0,0]
                if(res_image[j][k]==2):
                    color[j][k] = [0,128,0]
                if(res_image[j][k]==3):
                    color[j][k] = [128,128,0] 
                if(res_image[j][k]==4):
                    color[j][k] = [0,128,128]
                if(res_image[j][k]==5):
                    color[j][k] = [64,0,0]
                if(res_image[j][k]==6):
                    color[j][k] = [192,0,0]
                if(res_image[j][k]==7):
                    color[j][k] = [128,64,64]
                if(res_image[j][k]==9):
                    color[j][k] = [0,64,128]
        labeled_colorimages.append(color)
    

['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
['fr1', '__version__', '__header__', '__globals__']
[[11]
 [16]
 [21]
 [26]
 [29]
 [31]
 [33]
 [36]
 [41]
 [46]
 [51]]
['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
['fr1', '__version__', '__header__', '__globals__']
[[11]
 [16]
 [21]
 [26]
 [29]
 [31]
 [33]
 [36]
 [41]
 [46]
 [51]]
['automaticLayersNormal', 'automaticLayersDME', 'grader2', 'manualLayers1', '__header__', '__globals__', 'manualLayers2', 'grader1', 'images', 'grader_SJ', '__version__']
(61, 496, 768)
(61, 496, 768)
(61, 8, 768)
(61, 8, 768)
['fr1', '__version__', '__header__', '__globals__']
[[11]
 [16]
 [21]
 [26]
 [29]

In [6]:
print (len(labeled_images))

110


In [33]:
label_images = []
for i in range(len(labeled_images)) :
        for j in range(7) :
            label_image = crop_image(labeled_images[i],j*64,(j+1)*64)
            label_images.append(label_image)

In [34]:
np.save("resized_labels.npy", np.array(label_images))

In [7]:
print (len(images_modified))

110


In [8]:
print (labeled_images[0].shape)

(496, 496)


In [9]:
print (len(labeled_colorimages))

110


In [10]:
print (labeled_colorimages[0])

[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 ..., 
 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  ..., 
  [ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]]


In [11]:
for item in range(110):
    imsave('Dataset/Colored/Colored_'+str(item+1)+'.png',labeled_colorimages[item])
for item in range(110):
    imsave('Dataset/Train_images_original/train_'+str(item+1)+'.png',images_modified[item])

In [12]:
for i in range(110):
    for j in range(7):
        temp = crop_image(labeled_colorimages[0],j*64,(j+1)*64)
        imsave('Dataset/Colored_cropped/color_'+str((i*5)+(j+1))+'.png',temp)

In [13]:
print (images_modified[0].shape)

(496, 496)


In [14]:
train_images = []
dummy_train_labels = []


In [15]:
for i in range(len(images_modified)) :
        for j in range(7) :
            train_image = crop_image(images_modified[i],j*64,(j+1)*64)
            train_images.append(train_image)

In [16]:
print (len(train_images))

770


In [17]:
for item in range(len(train_images)) :
    imsave('Dataset/Train_images/image_'+str(item+1)+'.png',train_images[item])

In [18]:
for i in range(len(labeled_images)) :
    for j in range(7) :
        dummy_train_label = crop_image(labeled_images[i],j*64,(j+1)*64)
        dummy_train_labels.append(dummy_train_label)

In [19]:
print (len(dummy_train_labels))

770


In [20]:
print (dummy_train_labels[0].shape)

(496, 64)


In [21]:
train_labels  = np.zeros((770,496,64,8))

In [22]:
print (dummy_train_labels[0][0][0])

0.0


In [23]:
for i in range(len(dummy_train_labels)) :
    for j in range(496) :
        for k in range(64):
            if(dummy_train_labels[i][j][k] == 0):
                train_labels[i][j][k][0] = 1
            if(dummy_train_labels[i][j][k] == 1):
                train_labels[i][j][k][1] = 1
            if(dummy_train_labels[i][j][k] == 2):
                train_labels[i][j][k][2] = 1
            if(dummy_train_labels[i][j][k] == 3):
                train_labels[i][j][k][3] = 1
            if(dummy_train_labels[i][j][k] == 4):
                train_labels[i][j][k][4] = 1
            if(dummy_train_labels[i][j][k] == 5):
                train_labels[i][j][k][5] = 1
            if(dummy_train_labels[i][j][k] == 6):
                train_labels[i][j][k][6] = 1
            if(dummy_train_labels[i][j][k] == 7):
                train_labels[i][j][k][7] = 1

In [24]:
dummy_train_labels[0].shape

(496, 64)

In [25]:
count = [0]*8
weighted_images = []
for i in range(770):
    image = dummy_train_labels[i]
    weighted_image = np.zeros((496,64))
    for j in range(216):
        for k in range(64):
             if(image[j][k]==1):
                w2 = 11.459
             elif(image[j][k] == 2):
                w2 = 5.63
             elif(image[j][k]== 3):
                w2 = 11.007 
             elif(image[j][k] == 4):
                w2 = 14.368 
             elif(image[j][k]== 5):
                w2 = 3.336 
             elif(image[j][k]== 6):
                w2 = 13.647 
             elif(image[j][k]== 7):
                w2 = 16.978 
             else:
                w2 = 0
             if(j!=0 and j!=215):
                if(image[j+1][k]-image[j-1][k]>0 and w2<>0):
                    w1 = 15 
                   # count = count +1
                    count[int(image[j-1][k])] = count[int(image[j-1][k])] + 1 
                else:
                    w1 = 0
             else:
                w1 = 0
             w = 1 + w1 + w2
             weighted_image[j][k] = w
    weighted_images.append(weighted_image)

In [26]:
for item in range(770):
    imsave('Dataset/Weighted/weighted_'+str(item+1)+'.png',weighted_images[item])

In [27]:
np.save('weighted_cropped_images.npy',np.array(weighted_images))